#question 3 task 1
BREAD = 2.50
PEANUT_BUTTER = 3
JELLY = 2.50
COST_FOR_ITEMS = BREAD + PEANUT_BUTTER + JELLY
print(COST_FOR_ITEMS)

#question 3 task 2

SAVINGS_ACCOUNT = 10000
YEARLY_INTEREST_RATE = 7 * 100
TOTAL_SAVINGS_AMOUNT = SAVINGS_ACCOUNT + YEARLY_INTEREST_RATE
print(TOTAL_SAVINGS_AMOUNT)